language: python
python:
- 3.6
- 3.7
- 3.8
install: pip install --upgrade tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: fepegar
  password:
    secure: WJyYipT3Xx9dckWy89bfImq8PMZSCcTozmwxWDukuRKFzXb/lxQXCFPWqUfjWXhVRqSJ7isAETheIOyhpCdDQmUqZUMp7bIjwD3wF/RMvfrV/VredHzW/TuVLPLYref0/mnDgIBAMIl5aG/hvP67ZZBVrMS/ESAF41T01iE1w1G8o3s4BxVex9xTISkaSE0k5cnTtC5xhBIsp2s0JbbZFQiAaN7xFhBiBefjofFKaVHlJnxUi+HXtU+owucUotaWaqR5pmCFky4cK5FQSuNHuSBJq3J6EibWntJyQF+jTRsaTsGW87SETdOczSRm6saPc9/+vRTqzemaVTHe11/Kcy1ATRlycmi9YBw2DXaVq4O/DKExvs0cCSd3E7d3ec2DJ34UOpx9U+gBWQyjHDvs75Il/AGc6x97QufEqKEKvpJxrsY7m1+Os2JY2pFXKPPNvHYzVFe1vkCVgZHF//KnTOadbinHGuK3uj1618G6jh6iQJe44s7qmcWqvu8Xwptci+u9vE7uxy+GDRhtShE7MOYg+LqDW2Xeby5YC6eEbdBcBtn1Tz6XC+YEVYHK/jWwj5b3F9ljVQj18a0e+je4nhawEuPrG8E1r94d92lV5xD6Lek9Pn0TyQEpWwuyW3q+LNsJMvolrzk+gkvHMLMprS68wJZvD+NPjg/TSDwSIxk=
  on:
    tags: true
    repo: fepegar/resseg
    python: 3.7
